# Generated by Django 2.2.14 on 2020-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, null=True, to='guests.Guest'),
        ),
    ]
