# Generated by Django 2.2.14 on 2020-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakers', '0001_initial'),
        ('events', '0002_event_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, null=True, to='speakers.Speaker'),
        ),
    ]
