# Generated by Django 2.2.14 on 2020-09-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='delegates',
            field=models.ManyToManyField(blank=True, to='delegates.Delegate'),
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, to='guests.Guest'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='speakers.Speaker'),
        ),
    ]
