# Generated by Django 2.2.14 on 2020-09-07 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('your_name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('organization', models.TextField()),
                ('issue', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
