# Generated by Django 2.2.10 on 2020-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_subject',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
