# Generated by Django 2.2.10 on 2020-05-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_newsletter_newsletter_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='newsletter_subject',
        ),
    ]
