# Generated by Django 2.2.10 on 2020-05-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_remove_newsletter_newsletter_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
