# Generated by Django 3.0.2 on 2020-02-29 13:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boreholes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.BigIntegerField()),
                ('rate', models.FloatField()),
                ('total', models.FloatField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreholes.Meter')),
            ],
        ),
    ]
