# Generated by Django 2.2.5 on 2020-03-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreholes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borehole',
            name='fetched_historical',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
