# Generated by Django 2.2.5 on 2020-03-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreholes', '0002_borehole_fetched_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borehole',
            name='fetched_historical',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
