# Generated by Django 2.2.5 on 2020-03-08 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boreholes', '0003_auto_20200308_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('account_no', models.CharField(max_length=256)),
                ('payment_method', models.CharField(max_length=256)),
                ('borehole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreholes.Borehole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
