# Generated by Django 2.2.10 on 2020-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20200505_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='special_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
