# Generated by Django 3.0.3 on 2020-02-03 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee2020',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('mpesa_code', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
