# Generated by Django 2.2.5 on 2020-02-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee2020',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
