# Generated by Django 2.2.5 on 2020-02-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200226_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee2020',
            name='gak_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
