# Generated by Django 2.2.5 on 2020-02-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_attendee2020_gak_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee2020',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
